### ISSUE TITLE
Bump `@embroider/macros`

### ISSUE THREAD

**Issue by bertdeblock** [GavinJoyce/ember-headlessui#130]
The version currently used by `ember-headlessui` causes a build error for me post install.

ember-cli: 4.1.1
node: 16.13.2
os: darwin arm64

**Comment by bertdeblock** [comment]
This in turn also needs a bump of `ember-element-helper` it seems.

**Comment by NullVoxPopuli** [comment]
it does -- but also, we should remove render-modifiers from this addon

**Comment by bertdeblock** [comment]
What are the errors? Apologies if they are caused by my last PR.

**Comment by NullVoxPopuli** [comment]
all `@embroider/*` deps need to be in-sync across a whole project.
So, the solution folks should use for the time being is:
`resolutions` (for yarn)
`overrides` (for npm 8+)

to force embroider deps to be all 1.2.0
