### ISSUE TITLE
Implement <ComboBox> component

### ISSUE THREAD

**Issue by dmcnamara-eng** [GavinJoyce/ember-headlessui#138]
I am starting work on porting [ComboBox](https://headlessui.dev/react/combobox) to `ember-headlessui`

**Comment by dmcnamara-eng** [comment]
WIP: https://github.com/GavinJoyce/ember-headlessui/compare/master...phorest:feature/combobox?expand=1

**Comment by NullVoxPopuli** [comment]
this is exciting!! thank you!
