### ISSUE TITLE
`Dialog` breaks Ember-dispatched `click` events

### ISSUE THREAD

**Issue by alexlafroscia** [GavinJoyce/ember-headlessui#48]
While migrating our app's modal to use `Dialog` instead of `ember-modal-dialog`, I ran into something of an odd bug! Many `click` handlers in our app suddenly broke.

As it turns out, any `click` event dispatched through Ember's internal event-delegation mechanism are no longer fired. This includes `Ember.Component` classes that define the `click` method (which is attached to the root element) and any usage of the `{{action}}` modifier with the default configuration.

This ends up making sense, sort of -- `Dialog` stops propagation of the `click` event outside of the `Dialog` element. The Ember-event-dispatching system listens for events on the app root (`.ember-application`) and then dynamically dispatches the event back to the listener by looking at `event.target`. Because the event is not allowed to propagate up to `.ember-application`, the click events end up "blocked", even if they come from inside `Dialog`.

Note: this does not impact the `{{on}}` modifier, so modern code is fine, but it's difficult to integrate this component into a legacy codebase without doing a _ton_ of refactoring to remove every usage of Ember's event-dispatching system related to `click` events.

Additionally, because the `Dialog` is projected directly beneath the `.ember-application` element, stopping propagation does _not_ have the probably-intended affect of preventing click events "behind" the `Dialog`, since the app "behind" the `Dialog` is actually adjacent to it. So really the _only_ events that have propagation cancelled on them are the ones that are headed for `.ember-application` and Ember's event delegation system.

Whether and how to fix this might be tricky... I think that just removing the propagation-stopping might be fine, but there might be something more fancy we can do to achieve the same result.

**Comment by achambers** [comment]
hrm.....Nice write up @alexlafroscia . That sure is a doozy. I didn't consider that at all :(

> Additionally, because the Dialog is projected directly beneath the .ember-application element, stopping propagation does not have the probably-intended affect of preventing click events "behind" the Dialog, since the app "behind" the Dialog is actually adjacent to it. So really the only events that have propagation cancelled on them are the ones that are headed for .ember-application and Ember's event delegation system.

This alone sure makes the `stopPropagation` feel pointless anyway. And, thinking about it, I implemented the "portaling" towards the end, and so, the `stopPropagation` is possibly a hangover from the pre-portal implementation and maybe now doesn't really make that much sense. So, _maybe_ removing it is the way to go?!? 🤷‍♀️

**Comment by alexlafroscia** [comment]
> I didn't consider that at all

I wouldn't have either! I only came across all of this because our's is an old, old app with a lot of legacy components that use these patterns.

I think removing it is probably the way to go, too! Ideally an app would _just_ use the `{{on}}` modifier, but I don't know how common it really is these days that people have no hold-overs of the legacy patterns that end up breaking here.

**Comment by achambers** [comment]
@alexlafroscia So, just to clarify, this only affects the following types of code?

#### Components that extend `Ember.Component` and implement the `click` action
```js
import Component from '@ember/component';

export default class MyComponent extends Component {
  click() {
    //do something
  }
}
```

#### Templates that use the `{{action "click"}}` helper
```hbs
<button {{action "click" this.doSomething}}>Trigger</button>
```

**Comment by alexlafroscia** [comment]
Yup!

The `{{action}}` helper is even more insidious, as you usually will just invoke it like so

```hbs
<button {{action this.doSomething}}>Trigger</button>
```

which _implicitly_ binds a `click` event through Ember's event delegation system, so there's very few clues that the `event.stopPropagation` is the reason none of your actions are being called anymore!
