### ISSUE TITLE
🐛  `<Menu>` focus button after close items

### ISSUE THREAD

**Issue by far-fetched** [GavinJoyce/ember-headlessui#52]
Clicking outside the menu items should close menu, and focus button.

[Test](https://github.com/GavinJoyce/ember-headlessui/blob/master/tests/integration/components/menu-test.js#L539)

[Code](https://github.com/GavinJoyce/ember-headlessui/blob/master/addon/components/menu.js#L36)

Bug:

### **Steps to reproduce the problem**

* menu is rendered on the dialog, 
* clicking outside dialog (close dialog and menu)

### **What went wrong?**

* Button doesn't exist and cannot be focused.

<img width="553" alt="Captura de pantalla 2021-06-15 a las 9 52 05" src="https://user-images.githubusercontent.com/11621383/122014855-df13da80-cdbf-11eb-9d25-9652d7f14d06.png">

https://user-images.githubusercontent.com/11621383/122016204-1e8ef680-cdc1-11eb-979e-238beedb3c8a.mov

### **What is the expected behavior?**

Does not focus anything ?

**Comment by GavinJoyce** [comment]
Thanks for the bug report.

We should probably check to see if the element exists and only set focus if it does
