### ISSUE TITLE
`<Menu>` doesn't close items dropdown on `Escape`

### ISSUE THREAD

**Issue by achambers** [GavinJoyce/ember-headlessui#54]
We should make the `<Menu>` dropdown close when Escape is hit. I suspect it should go here.

https://github.com/GavinJoyce/ember-headlessui/blob/57f3da16050f1eeb608d9a2bbea993c75e24c857/addon/components/menu/items.js#L6-L20

**Comment by alexlafroscia** [comment]
I'm making some other improvements to `Menu` right now, including implementing the item search functionality. I'll take care of this one!
