### ISSUE TITLE
Should we add this project to hacktoberfest?

### ISSUE THREAD

**Issue by NullVoxPopuli** [GavinJoyce/ember-headlessui#96]
According to the [maintainers' resources page](https://hacktoberfest.digitalocean.com/resources/maintainers), all that needs to happen is adding `Hacktoberfest` to the repo's topics

**Comment by GavinJoyce** [comment]
✅ 

<img width="434" alt="Screenshot 2021-10-03 at 21 08 52" src="https://user-images.githubusercontent.com/2526/135769850-a554c9e7-969e-44be-8883-234917eeb953.png">

**Comment by NullVoxPopuli** [comment]
woo! now let's hope people want a t-shirt :D

**Comment by tniezurawski** [comment]
From the page posted by @NullVoxPopuli:

> Apply the 'Hacktoberfest' label to issues in your GitHub or GitLab project that are ready for contributors to work on.

@GavinJoyce Do you see issues where that could easily fit? 🤔

**Comment by GavinJoyce** [comment]
Hmm, yeah - now that I think of it there aren't many issues that people can just pick up. Probably just this one:

 * https://github.com/GavinJoyce/ember-headlessui/issues/77

I haven't participated in Hacktoberfest before so haven't really thought about the implications of adding the tag. We could remove it if we think we're not suitable

**Comment by NullVoxPopuli** [comment]
I still think it makes sense for folks who already know ember + tailwind and want the goals of headless UI 🤷 might be a small group? but in my past years participating in hacktoberfest _most_ issues are documentation related (as writing documentation requires a fair bit less context than coding), and we could always use more of that.
